name: flutter_observation_example
description: Example app for flutter_observation.
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_observation: ^0.2.0

dev_dependencies:
  build_runner: 2.15.1
  flutter_observation_generator: ^0.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
