builders:
  observable:
    import: "package:flutter_observation_generator/builder.dart"
    builder_factories: ["observableBuilder"]
    build_extensions: {".dart": [".observable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
